eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: qa

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profile: uat

---
spring:
  config:
    activate:
      on-profile: prod
